apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-k8s-package
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/intelops/capten-templates.git
    targetRevision: main
    path: infra/crossplane/packages-def/k8s/aws
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
